# Generated by Django 5.0.6 on 2024-05-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencing_factory', models.CharField(max_length=256)),
                ('sequencing_location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=256)),
                ('entity', models.CharField(max_length=256)),
                ('start', models.IntegerField(blank=True)),
                ('stop', models.IntegerField(blank=True)),
                ('sense', models.CharField(max_length=1)),
                ('start_codon', models.CharField(default='M', max_length=1)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioapp.ec')),
                ('sequencing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioapp.sequencing')),
            ],
        ),
        migrations.CreateModel(
            name='GeneAttributeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioapp.attribute')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioapp.gene')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='gene',
            field=models.ManyToManyField(through='bioapp.GeneAttributeLink', to='bioapp.gene'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('product', models.CharField(max_length=256)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioapp.gene')),
            ],
        ),
    ]
