# Generated by Django 5.0.6 on 2024-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
