# Generated by Django 5.0.6 on 2024-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioapp', '0002_alter_gene_gene_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
